### ISSUE TITLE
Crash while mobs rebirth after death

### ISSUE THREAD

**Issue by DatrixTHLK** [The-Fireplace/Mob-Rebirth#10]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
Minecraft: 1.14.4
Forge: 28.0.93
Mob Rebirth: 8.0.1
 * For any issue, providing your fml-client-latest.log or fml-server-latest.log can be very helpful. If you have one of these, please paste it to [GIST](https://gist.github.com/DatrixTHLK/fce962b116b825bdfd6752a00ac1ef8d) and link it here.
 * If you crashed, please paste the crash log to [GIST](https://gist.github.com/DatrixTHLK/cee588a687d270f5380552025e7bd282) and link it here.

**Comment by The-Fireplace** [comment]
I'll get it fixed when I get the chance, you might try an older Forge version until then.

**Comment by DatrixTHLK** [comment]
Sounds good. I can wait, so no hurry. Thanks for the prompt response! I appreciate it.
