### ISSUE TITLE
No config file and game crash while mob rebirths or respawns after death

### ISSUE THREAD

**Issue by DatrixTHLK** [The-Fireplace/Mob-Rebirth#13]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
Minecraft: 1.14.4
Forge: 28.1.90
Mobrebirth: 8.0.2

 * For any issue, providing your fml-client-latest.log or fml-server-latest.log can be very helpful. If you have one of these, please paste it to [Ubuntu Pastebin](https://paste.ubuntu.com/) or [Gist](https://gist.github.com/DatrixTHLK/c3452b7f5c1241b7ff0eef6d21beb440) and link it here.

 * If you crashed, please paste the crash log to [Ubuntu Pastebin](https://paste.ubuntu.com/) or [Gist](https://gist.github.com/DatrixTHLK/d61c235af21f78680b032b897d2c1920) and link it here.

Just a side note I haven't seen hide nor hair of a config file within the config folder where I thought the config file should show up. Pictureed below:
![Config Folder](https://user-images.githubusercontent.com/13172036/68987698-fc568080-07f9-11ea-9d36-4db59a3650bf.png)

**Comment by The-Fireplace** [comment]
The mod uses server config on 1.14.4, so the file is in your world/config (or world/serverconfig, I forget which) folder.

**Comment by DatrixTHLK** [comment]
Ok I'll take a look in there where ever that maybe. 

**Edit:** Found the config file within the serverconfig folder within the world folder within the saves folder as you said.

**Comment by The-Fireplace** [comment]
Try again with 8.1.1.
