### ISSUE TITLE
[1.15.2] Rebirth works, but instead the fall from too high and die.

### ISSUE THREAD

**Issue by realTIMematrix** [The-Fireplace/Mob-Rebirth#14]
Hi,

I'm using:

Minecraft: 1.15.2
Forge: 31.0.14
MobRebirth: 1.15.2-8.1.0

Issue:

I set up the setting to nearly 90% of respawn and set the multimob to 50%. Pretty insane how fast you can crash the game with to many entities ;-)

But what i see is that the additional mobs drop and die immediatly and this produces more mobs with the noplayerkill=true setting.... Ok...

Is there another way how mobs spawn instead of dropping from sky?

**Comment by The-Fireplace** [comment]
They aren't supposed to drop from the sky 😂
I'll get that fixed ASAP

**Comment by The-Fireplace** [comment]
Fixed in 8.1.1
